lsi: false
safe: true
source: C:\Users\ethan\OneDrive\Documents\GitHub\4owo.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge